### ISSUE TITLE
I think need fix get_local_ip() function.

### ISSUE THREAD

**Issue by bongdang** [bdraco/aiodiscover#25]
Hi.

get_local_ip function in network.py doing some wired action.
Connecting to "(10.255.255.255", 1) generate exception in my env. How about change to ("8.8.8.8", 1)?
My env ls 10.X.X.X  private IP networks.

Thanks.

## Reproduction
*A minimal example that exhibits the behavior.*

## Environment
*Any additional information about your environment*

**Comment by bdraco** [comment]
Fixed via #26

**Comment by bongdang** [comment]
Still got Exception.

>>> s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
>>> s.setblocking(False)
>>> s.connect(('10.255.255.255',1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
PermissionError: [Errno 13] Permission denied

as above.

2022년 4월 18일 (월) 오전 11:26, J. Nick Koston ***@***.***>님이 작성:

**Comment by bdraco** [comment]
Please see
https://github.com/bdraco/aiodiscover/blob/main/aiodiscover/network.py#L162

**Comment by bongdang** [comment]
Sorry. I didn't view all source. ;)
Thank you for your job. I think it's better.

Have a nice day!

2022년 4월 18일 (월) 오후 4:54, J. Nick Koston ***@***.***>님이 작성:
